### ISSUE TITLE
Hello, @HuoTeng

### ISSUE THREAD

**Issue by coderhaoxin** [HuoTeng/Demo#1]
@HuoTeng 你好，我是百姓网的`郝鑫`，从你的简历看到这个 Repo.
你可以把百姓 Demo 弄个简易的 React 版不？(就像目前这样只要个首页就行啦)

- [ ] 使用 `ES6 module`, `Class 风格的 React Component`
- [ ] 使用 `webpack` 打包, `babel` 编译, `postcss` 预处理 css

**Comment by coderhaoxin** [comment]
个人建议单独放一个目录

```
|Demo
--|baixing
----|client
```

**Comment by HuoTeng** [comment]
不好意思，刚刚才看到这条信息。
要求什么时候完成呢，你说的这些技术我之前没用过，仅仅看过，不过我可以尝试一下。

**Comment by coderhaoxin** [comment]
> 不好意思，刚刚才看到这条信息。

哈哈，我issue 很晚才open的 :cry: 

> 要求什么时候完成呢

没有一个硬性的截止时间，下周一吧

**Comment by HuoTeng** [comment]
嗯嗯，好的。

**Comment by HuoTeng** [comment]
@coderhaoxin 你好，React版我写好啦。
由于在实习，周末才开始写的，有点匆忙，不合适的地方麻烦你多提点建议，谢谢。

**Comment by coderhaoxin** [comment]
嗯嗯，已经看到了。
